### ISSUE TITLE
[DataCap Application] Allen Institute

### ISSUE THREAD

**Issue by usejsi** [filplus-bookkeeping/IPFSCN#19]
### Version

1

### DataCap Applicant

Allen Institute

### Project ID

01

### Data Owner Name

Allen Institute

### Data Owner Country/Region

China

### Data Owner Industry

Life Science / Healthcare

### Website

https://registry.opendata.aws/?search=managedBy:allen%20institute

### Social Media Handle

https://registry.opendata.aws/?search=managedBy:allen%20institute

### Social Media Type

Other

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

3PiB

### Expected size of single dataset (one copy)

512TiB

### Number of replicas to store

6

### Weekly allocation of DataCap requested

512TiB

### On-chain address for first allocation

f1d5rtlrw54nbf7tmzciohfmz7zbevqquqdcoy6dy

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
I'm the tech lead for pubang and would like to bring more public data to filecoin
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
This registry exists to help people discover and share datasets that are available via AWS resources. See recent additions and learn more about sharing data on AWS.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

China

### Please share a sample of the data

```text
aws s3 ls --no-sign-request s3://allen-brain-observatory/   158.8 TiB
aws s3 ls --no-sign-request s3://allen-mouse-brain-atlas/ 190.0 TiB
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), IPFS, Shipping hard drives, Lotus built-in data transfer

### How did you find your storage providers

Slack, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f02822222 Hong Kong
f02368946 Beijing
f02362412 California
f02639492 California
f03166666 Hongkong
f03166668 Hongkong
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by a1991car** [comment]
The application mentions plans to store data in multiple geographic locations, including 'Greater China', 'Asia other than Greater China', and 'North America'. Please provide a detailed explanation of the reasons for choosing these specific geographic locations, as well as how to ensure the compliance and security of data in these areas.
